-- =====================================================================
-- Cubby: daycare management schema, draft v0.1 (PostgreSQL 14+)
--
-- Sections
--   1. Tenancy, users, audit
--   2. Classrooms and children
--   3. Families, contacts, health alerts, documents
--   4. Attendance
--   5. Staff, certifications, time clock
--   6. Billing
--   7. Food program (CACFP): reference data, menus, meal service,
--      per-child meal records, eligibility, rates, monthly claims
--   8. Views
--
-- Conventions
--   * UUID primary keys, generated by the database or by the client
--     (client-generated ids let tablets log meals offline and sync safely).
--   * Money is stored as integer cents, except reimbursement rates,
--     which the USDA publishes to four decimal places.
--   * Every table that belongs to a center carries center_id so that
--     row-level security can isolate one center from another.
--   * Rows that feed a state claim are snapshotted (age group,
--     eligibility category, rate) so a past claim can always be
--     reproduced, even after a birthday or a rate change.
--   * Reference tables that mirror USDA or NJ rules (meal patterns,
--     rates, age groups) are data, not code, so rule changes are updates.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;   -- no-overlap constraints on date ranges

-- ---------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------
CREATE TYPE user_role            AS ENUM ('owner','director','teacher','billing','cook','parent');
CREATE TYPE child_status         AS ENUM ('waitlist','active','withdrawn');
CREATE TYPE alert_kind           AS ENUM ('allergy','medical','dietary');
CREATE TYPE alert_severity       AS ENUM ('mild','moderate','severe');
CREATE TYPE contact_role         AS ENUM ('authorized_pickup','emergency');
CREATE TYPE document_type        AS ENUM ('medical_statement','eligibility_form','immunization','enrollment_form',
                                          'certification','background_check','menu_label','other');
CREATE TYPE attendance_status    AS ENUM ('present','absent');
CREATE TYPE invoice_status       AS ENUM ('draft','open','paid','void');
CREATE TYPE invoice_line_type    AS ENUM ('tuition','fee','discount','credit');
CREATE TYPE payment_method       AS ENUM ('card','bank_transfer','check','cash','subsidy');
CREATE TYPE meal_type            AS ENUM ('breakfast','am_snack','lunch','pm_snack','supper','evening_snack');
CREATE TYPE eligibility_category AS ENUM ('free','reduced','paid');
CREATE TYPE eligibility_method   AS ENUM ('income_application','categorical','foster','head_start','other');
CREATE TYPE amount_eaten         AS ENUM ('none','some','half','most','all');
CREATE TYPE meal_service_status  AS ENUM ('open','finalized');
CREATE TYPE child_meal_status    AS ENUM ('served','declined','not_present');
CREATE TYPE substitution_reason  AS ENUM ('allergy','disability','religious','preference');
CREATE TYPE feeding_type         AS ENUM ('breast_milk','formula','solid','other');
CREATE TYPE supplied_by          AS ENUM ('center','parent');
CREATE TYPE claim_status         AS ENUM ('draft','validated','submitted','accepted','adjusted','rejected');
CREATE TYPE issue_severity       AS ENUM ('error','warning');

-- =====================================================================
-- 1. TENANCY, USERS, AUDIT
-- =====================================================================
CREATE TABLE centers (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name            text NOT NULL,
  license_number  text,                       -- state child care license
  address_line1   text,
  city            text,
  state           char(2) NOT NULL DEFAULT 'NJ',
  postal_code     text,
  phone           text,
  timezone        text NOT NULL DEFAULT 'America/New_York',
  closing_time    time NOT NULL DEFAULT '18:00',
  late_fee_cents  integer NOT NULL DEFAULT 1500,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id     uuid NOT NULL REFERENCES centers(id),
  email         text NOT NULL UNIQUE,
  auth_subject  text,                          -- id from your identity provider; do not store raw passwords
  role          user_role NOT NULL,
  is_active     boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
  -- staff_id / guardian_id links are added below, after those tables exist
);

-- Append-only record of who changed what. Essential for state audits,
-- especially edits to meal records after a day has been finalized.
CREATE TABLE audit_log (
  id           bigserial PRIMARY KEY,
  center_id    uuid REFERENCES centers(id),
  user_id      uuid REFERENCES users(id),
  occurred_at  timestamptz NOT NULL DEFAULT now(),
  action       text NOT NULL,                  -- insert | update | delete | finalize | reopen | submit
  table_name   text NOT NULL,
  record_id    uuid,
  before_data  jsonb,
  after_data   jsonb,
  reason       text                            -- required by the app when reopening finalized data
);
CREATE INDEX audit_log_record_idx ON audit_log (table_name, record_id);

-- =====================================================================
-- 2. CLASSROOMS AND CHILDREN
-- =====================================================================
CREATE TABLE classrooms (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id                uuid NOT NULL REFERENCES centers(id),
  name                     text NOT NULL,
  color_hex                text,
  min_age_months           smallint,
  max_age_months           smallint,
  ratio_children_per_staff smallint NOT NULL CHECK (ratio_children_per_staff > 0),  -- licensing limit
  max_group_size           smallint,
  is_active                boolean NOT NULL DEFAULT true,
  UNIQUE (center_id, name)
);

CREATE TABLE billing_accounts (                -- one per family; defined here so children can reference it
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id      uuid NOT NULL REFERENCES centers(id),
  family_name    text NOT NULL,
  status         text NOT NULL DEFAULT 'active',
  autopay_token  text,                         -- processor token only, never card numbers
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE children (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id          uuid NOT NULL REFERENCES centers(id),
  billing_account_id uuid REFERENCES billing_accounts(id),
  first_name         text NOT NULL,
  last_name          text NOT NULL,
  preferred_name     text,
  date_of_birth      date NOT NULL,
  status             child_status NOT NULL DEFAULT 'active',
  enrolled_on        date,
  withdrawn_on       date,
  photo_consent      boolean NOT NULL DEFAULT false,
  notes              text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  CHECK (withdrawn_on IS NULL OR enrolled_on IS NULL OR withdrawn_on >= enrolled_on)
);
CREATE INDEX children_center_idx ON children (center_id, status);

-- Room history. A child is in exactly one room on any given day.
CREATE TABLE child_classroom_assignments (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id      uuid NOT NULL REFERENCES children(id),
  classroom_id  uuid NOT NULL REFERENCES classrooms(id),
  valid_during  daterange NOT NULL,            -- upper bound NULL/infinity = current room
  EXCLUDE USING gist (child_id WITH =, valid_during WITH &&)
);

-- =====================================================================
-- 3. FAMILIES, CONTACTS, HEALTH ALERTS, DOCUMENTS
-- =====================================================================
CREATE TABLE guardians (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id     uuid NOT NULL REFERENCES centers(id),
  first_name    text NOT NULL,
  last_name     text NOT NULL,
  email         text,
  phone_mobile  text,
  phone_alt     text,
  address_line1 text,
  city          text,
  state         char(2),
  postal_code   text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- Many-to-many: siblings share guardians, and a child can have several guardians.
CREATE TABLE child_guardians (
  child_id              uuid NOT NULL REFERENCES children(id),
  guardian_id           uuid NOT NULL REFERENCES guardians(id),
  relationship          text NOT NULL,         -- mother, father, foster parent, ...
  is_primary            boolean NOT NULL DEFAULT false,
  lives_with_child      boolean NOT NULL DEFAULT true,
  can_pick_up           boolean NOT NULL DEFAULT true,
  is_emergency_contact  boolean NOT NULL DEFAULT true,
  is_billing_responsible boolean NOT NULL DEFAULT false,
  can_view_portal       boolean NOT NULL DEFAULT true,
  PRIMARY KEY (child_id, guardian_id)
);

-- People who are not guardians: grandparents, neighbors, aunts, and so on.
CREATE TABLE contacts (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id   uuid NOT NULL REFERENCES centers(id),
  first_name  text NOT NULL,
  last_name   text NOT NULL,
  phone       text
);
CREATE TABLE child_contacts (
  child_id          uuid NOT NULL REFERENCES children(id),
  contact_id        uuid NOT NULL REFERENCES contacts(id),
  role              contact_role NOT NULL,
  relationship      text NOT NULL,
  photo_id_on_file  boolean NOT NULL DEFAULT false,
  priority          smallint NOT NULL DEFAULT 1,
  PRIMARY KEY (child_id, contact_id, role)
);

CREATE TABLE child_health (
  child_id             uuid PRIMARY KEY REFERENCES children(id),
  pediatrician_name    text,
  pediatrician_clinic  text,
  pediatrician_phone   text,
  immunizations_current boolean,
  immunization_due_on  date,
  notes                text
);

CREATE TABLE allergens (                        -- reference list, seeded (major food allergens)
  code   text PRIMARY KEY,                     -- milk, egg, peanut, tree_nut, soy, wheat, fish, shellfish, sesame
  label  text NOT NULL
);

CREATE TABLE documents (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id    uuid NOT NULL REFERENCES centers(id),
  child_id     uuid REFERENCES children(id),
  doc_type     document_type NOT NULL,
  title        text NOT NULL,
  storage_key  text NOT NULL,                  -- object-store key; files never live in the database
  uploaded_by  uuid REFERENCES users(id),
  uploaded_at  timestamptz NOT NULL DEFAULT now(),
  expires_on   date
);

CREATE TABLE child_alerts (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id             uuid NOT NULL REFERENCES children(id),
  kind                 alert_kind NOT NULL,
  name                 text NOT NULL,
  allergen_code        text REFERENCES allergens(code),   -- lets the meal screen flag matching foods
  severity             alert_severity NOT NULL,
  care_plan            text,
  medical_statement_id uuid REFERENCES documents(id),
  is_active            boolean NOT NULL DEFAULT true,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX child_alerts_child_idx ON child_alerts (child_id) WHERE is_active;

-- =====================================================================
-- 4. ATTENDANCE
-- One row per child per day. If you need several in/out sessions in a
-- day (leaves for an appointment and returns), split into a sessions table.
-- =====================================================================
CREATE TABLE attendance_records (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id               uuid NOT NULL REFERENCES centers(id),
  child_id                uuid NOT NULL REFERENCES children(id),
  classroom_id            uuid NOT NULL REFERENCES classrooms(id),   -- room that day (snapshot)
  service_date            date NOT NULL,
  status                  attendance_status NOT NULL,
  absence_reason          text,
  checked_in_at           timestamptz,
  checked_out_at          timestamptz,
  dropped_off_by_guardian uuid REFERENCES guardians(id),
  picked_up_by_guardian   uuid REFERENCES guardians(id),
  picked_up_by_contact    uuid REFERENCES contacts(id),
  photo_id_checked        boolean NOT NULL DEFAULT false,
  recorded_by             uuid REFERENCES users(id),
  notes                   text,
  UNIQUE (child_id, service_date),
  CHECK (checked_out_at IS NULL OR checked_in_at IS NULL OR checked_out_at >= checked_in_at),
  CHECK (NOT (picked_up_by_guardian IS NOT NULL AND picked_up_by_contact IS NOT NULL)),
  CHECK (status = 'absent' OR checked_in_at IS NOT NULL)
);
CREATE INDEX attendance_day_idx ON attendance_records (center_id, service_date);

-- =====================================================================
-- 5. STAFF, CERTIFICATIONS, TIME CLOCK
-- =====================================================================
CREATE TABLE staff (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id             uuid NOT NULL REFERENCES centers(id),
  first_name            text NOT NULL,
  last_name             text NOT NULL,
  job_title             text NOT NULL,          -- Director, Lead teacher, Assistant teacher, Cook, Floater
  email                 text,
  phone                 text,
  hired_on              date,
  terminated_on         date,
  default_classroom_id  uuid REFERENCES classrooms(id)
);

ALTER TABLE users
  ADD COLUMN staff_id    uuid REFERENCES staff(id),
  ADD COLUMN guardian_id uuid REFERENCES guardians(id),
  ADD CONSTRAINT users_one_identity CHECK (staff_id IS NULL OR guardian_id IS NULL);

CREATE TABLE certification_types (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id       uuid NOT NULL REFERENCES centers(id),
  code            text NOT NULL,               -- cpr_first_aid, background_check, mandated_reporter, health_screen, food_safety
  label           text NOT NULL,
  valid_months    smallint,
  required_for_all boolean NOT NULL DEFAULT true,
  UNIQUE (center_id, code)
);
CREATE TABLE staff_certifications (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id    uuid NOT NULL REFERENCES staff(id),
  cert_type_id uuid NOT NULL REFERENCES certification_types(id),
  issued_on   date,
  expires_on  date,
  document_id uuid REFERENCES documents(id)
);
CREATE INDEX staff_cert_expiry_idx ON staff_certifications (expires_on);

CREATE TABLE staff_shifts (                     -- planned schedule
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id      uuid NOT NULL REFERENCES staff(id),
  classroom_id  uuid REFERENCES classrooms(id),
  work_date     date NOT NULL,
  starts_at     time NOT NULL,
  ends_at       time NOT NULL,
  CHECK (ends_at > starts_at)
);

CREATE TABLE time_entries (                     -- actual clock in/out; open rows drive the ratio monitor
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id      uuid NOT NULL REFERENCES staff(id),
  classroom_id  uuid REFERENCES classrooms(id),   -- NULL while floating or in the office
  clock_in_at   timestamptz NOT NULL,
  clock_out_at  timestamptz,
  CHECK (clock_out_at IS NULL OR clock_out_at >= clock_in_at)
);
CREATE UNIQUE INDEX one_open_entry_per_staff ON time_entries (staff_id) WHERE clock_out_at IS NULL;

-- =====================================================================
-- 6. BILLING
-- =====================================================================
CREATE TABLE account_guardians (
  account_id   uuid NOT NULL REFERENCES billing_accounts(id),
  guardian_id  uuid NOT NULL REFERENCES guardians(id),
  is_payer     boolean NOT NULL DEFAULT true,
  PRIMARY KEY (account_id, guardian_id)
);

CREATE TABLE tuition_plans (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id     uuid NOT NULL REFERENCES centers(id),
  name          text NOT NULL,
  classroom_id  uuid REFERENCES classrooms(id),
  amount_cents  integer NOT NULL CHECK (amount_cents >= 0),
  period        text NOT NULL DEFAULT 'monthly' CHECK (period IN ('weekly','monthly')),
  valid_during  daterange NOT NULL
);
CREATE TABLE child_tuition (                    -- which plan a child is on, with optional overrides
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id              uuid NOT NULL REFERENCES children(id),
  plan_id               uuid NOT NULL REFERENCES tuition_plans(id),
  override_amount_cents integer,
  discount_percent      numeric(5,2) NOT NULL DEFAULT 0,       -- e.g., sibling discount
  valid_during          daterange NOT NULL,
  EXCLUDE USING gist (child_id WITH =, valid_during WITH &&)
);

CREATE TABLE fee_types (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id            uuid NOT NULL REFERENCES centers(id),
  code                 text NOT NULL,          -- late_pickup, supplies, field_trip, registration
  label                text NOT NULL,
  default_amount_cents integer NOT NULL DEFAULT 0,
  UNIQUE (center_id, code)
);

CREATE TABLE invoices (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id     uuid NOT NULL REFERENCES billing_accounts(id),
  invoice_number text NOT NULL UNIQUE,
  period_start   date NOT NULL,
  period_end     date NOT NULL,
  issued_on      date,
  due_on         date,
  status         invoice_status NOT NULL DEFAULT 'draft',
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE invoice_lines (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id           uuid NOT NULL REFERENCES invoices(id),
  child_id             uuid REFERENCES children(id),
  line_type            invoice_line_type NOT NULL,
  fee_type_id          uuid REFERENCES fee_types(id),
  description          text NOT NULL,
  quantity             numeric(8,2) NOT NULL DEFAULT 1,
  unit_amount_cents    integer NOT NULL,       -- negative for discounts and credits
  amount_cents         integer NOT NULL,
  source_attendance_id uuid REFERENCES attendance_records(id)   -- links an automatic late-pickup fee to the check-out
);
CREATE TABLE payments (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id       uuid NOT NULL REFERENCES billing_accounts(id),
  received_on      date NOT NULL,
  amount_cents     integer NOT NULL CHECK (amount_cents > 0),
  method           payment_method NOT NULL,
  reference        text,
  processor_txn_id text,
  receipt_number   text UNIQUE,
  created_by       uuid REFERENCES users(id),
  voided_at        timestamptz
);
CREATE TABLE payment_allocations (              -- one payment can cover several invoices
  payment_id    uuid NOT NULL REFERENCES payments(id),
  invoice_id    uuid NOT NULL REFERENCES invoices(id),
  amount_cents  integer NOT NULL CHECK (amount_cents > 0),
  PRIMARY KEY (payment_id, invoice_id)
);

-- =====================================================================
-- 7. FOOD PROGRAM (CACFP)
-- =====================================================================

-- 7a. Center enrollment in the program ---------------------------------
CREATE TABLE food_program_sites (
  center_id          uuid PRIMARY KEY REFERENCES centers(id),
  program            text NOT NULL DEFAULT 'CACFP',
  agreement_number   text,                     -- number from your state agreement
  sponsor_name       text,                     -- NULL if you contract directly with the state agency
  institution_type   text CHECK (institution_type IN ('nonprofit','proprietary','head_start','other')),
  meal_types_offered meal_type[] NOT NULL,
  max_meals_per_day  smallint NOT NULL DEFAULT 3,   -- program limit is two meals plus one snack, or one meal plus two snacks
  notes              text
);

-- 7b. Reference data: age groups, components, meal patterns, rates -----
CREATE TABLE cacfp_age_groups (
  id          smallint PRIMARY KEY,
  code        text NOT NULL UNIQUE,            -- infant_0_5, infant_6_11, age_1_2, age_3_5, age_6_12
  label       text NOT NULL,
  min_months  smallint NOT NULL,
  max_months  smallint NOT NULL                -- inclusive
);

CREATE TABLE food_components (
  code   text PRIMARY KEY,                     -- milk, vegetable, fruit, grain, meat_alt, breast_milk_formula, infant_cereal, ...
  label  text NOT NULL
);

-- What each meal must contain, by meal type and age group.
-- Seed from the current USDA meal pattern charts and update when they change.
-- For "any two of these components" snacks, rows share a choice_group and choose_n.
CREATE TABLE meal_patterns (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meal_type       meal_type NOT NULL,
  age_group_id    smallint NOT NULL REFERENCES cacfp_age_groups(id),
  component_code  text NOT NULL REFERENCES food_components(code),
  min_quantity    numeric(6,2) NOT NULL,
  unit            text NOT NULL,               -- fl oz, cup, oz eq, tbsp
  choice_group    smallint,
  choose_n        smallint,
  effective_from  date NOT NULL,
  effective_to    date,
  notes           text
);
CREATE INDEX meal_patterns_lookup_idx ON meal_patterns (meal_type, age_group_id, effective_from);

CREATE TABLE reimbursement_rates (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fiscal_year       smallint NOT NULL,         -- federal fiscal year; rates reset each July 1
  meal_type         meal_type NOT NULL,
  category          eligibility_category NOT NULL,
  rate_dollars      numeric(8,4) NOT NULL,
  effective_from    date NOT NULL,
  UNIQUE (fiscal_year, meal_type, category)
);

-- 7c. Foods, menus ----------------------------------------------------
CREATE TABLE food_items (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id           uuid NOT NULL REFERENCES centers(id),
  name                text NOT NULL,
  brand               text,
  primary_component   text REFERENCES food_components(code),
  credit_quantity     numeric(6,2),            -- how much of the component one serving credits
  credit_unit         text,
  whole_grain_rich    boolean,
  label_document_id   uuid REFERENCES documents(id),   -- product label or manufacturer statement
  is_active           boolean NOT NULL DEFAULT true
);
CREATE TABLE food_item_allergens (
  food_item_id   uuid NOT NULL REFERENCES food_items(id),
  allergen_code  text NOT NULL REFERENCES allergens(code),
  PRIMARY KEY (food_item_id, allergen_code)
);

CREATE TABLE menus (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id    uuid NOT NULL REFERENCES centers(id),
  name         text NOT NULL,
  week_start   date NOT NULL,
  published_at timestamptz,
  approved_by  uuid REFERENCES users(id),
  UNIQUE (center_id, week_start)
);
CREATE TABLE menu_meals (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  menu_id      uuid NOT NULL REFERENCES menus(id),
  service_date date NOT NULL,
  meal_type    meal_type NOT NULL,
  UNIQUE (menu_id, service_date, meal_type)
);
CREATE TABLE menu_meal_items (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  menu_meal_id    uuid NOT NULL REFERENCES menu_meals(id),
  food_item_id    uuid NOT NULL REFERENCES food_items(id),
  component_code  text NOT NULL REFERENCES food_components(code),
  age_group_id    smallint REFERENCES cacfp_age_groups(id),   -- NULL = applies to all age groups
  planned_quantity numeric(6,2),
  unit            text
);

-- 7d. Meal service: what the classroom actually served ----------------
-- One row per classroom per meal per day. This is the "production record":
-- what was put on the table, in what portion, for which age group.
CREATE TABLE meal_services (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id         uuid NOT NULL REFERENCES centers(id),
  classroom_id      uuid NOT NULL REFERENCES classrooms(id),
  service_date      date NOT NULL,
  meal_type         meal_type NOT NULL,
  planned_menu_meal_id uuid REFERENCES menu_meals(id),
  served_at         timestamptz,
  served_by_staff   uuid REFERENCES staff(id),
  status            meal_service_status NOT NULL DEFAULT 'open',
  finalized_at      timestamptz,
  finalized_by      uuid REFERENCES users(id),
  notes             text,
  UNIQUE (classroom_id, service_date, meal_type),
  CHECK (status = 'open' OR finalized_at IS NOT NULL)
);
CREATE INDEX meal_services_day_idx ON meal_services (center_id, service_date);

CREATE TABLE meal_service_items (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meal_service_id uuid NOT NULL REFERENCES meal_services(id),
  food_item_id    uuid NOT NULL REFERENCES food_items(id),
  component_code  text NOT NULL REFERENCES food_components(code),
  age_group_id    smallint REFERENCES cacfp_age_groups(id),
  portion_quantity numeric(6,2) NOT NULL,
  portion_unit    text NOT NULL,
  differs_from_menu boolean NOT NULL DEFAULT false,
  notes           text
);

-- 7e. Per-child meal records: the teacher's screen writes here --------
CREATE TABLE eligibility_determinations (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id            uuid NOT NULL REFERENCES children(id),
  category            eligibility_category NOT NULL,
  method              eligibility_method NOT NULL,
  effective_on        date NOT NULL,
  expires_on          date NOT NULL,           -- forms are renewed every year
  title_xx_subsidized boolean NOT NULL DEFAULT false,   -- used for the proprietary-center eligibility share
  verified_by         uuid REFERENCES users(id),
  document_id         uuid REFERENCES documents(id),
  -- Store only the outcome. Do not keep household income in this system unless you must;
  -- if you do, put it in a separate, tightly restricted table.
  CHECK (expires_on > effective_on)
);
CREATE INDEX eligibility_child_idx ON eligibility_determinations (child_id, effective_on DESC);

CREATE TABLE child_meal_records (
  id                     uuid PRIMARY KEY,     -- client-generated so offline tablets can sync without duplicates
  meal_service_id        uuid NOT NULL REFERENCES meal_services(id),
  child_id               uuid NOT NULL REFERENCES children(id),
  attendance_record_id   uuid REFERENCES attendance_records(id),
  -- Snapshots taken when the record is written
  age_group_id           smallint NOT NULL REFERENCES cacfp_age_groups(id),
  eligibility_category   eligibility_category NOT NULL,
  eligibility_determination_id uuid REFERENCES eligibility_determinations(id),
  -- What happened
  status                 child_meal_status NOT NULL,
  overall_amount_eaten   amount_eaten,
  -- Result of the rule check, computed by the server, never typed by hand
  is_claimable           boolean NOT NULL DEFAULT false,
  non_claim_reason       text,
  recorded_by            uuid REFERENCES users(id),
  recorded_at            timestamptz NOT NULL DEFAULT now(),
  device_id              text,
  notes                  text,
  UNIQUE (meal_service_id, child_id),
  CHECK (is_claimable = false OR status = 'served')
);
CREATE INDEX child_meal_records_child_idx ON child_meal_records (child_id, recorded_at);

-- Item-level detail: exactly what each child ate.
CREATE TABLE child_meal_items (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_meal_record_id  uuid NOT NULL REFERENCES child_meal_records(id) ON DELETE CASCADE,
  meal_service_item_id  uuid REFERENCES meal_service_items(id),
  food_item_id          uuid NOT NULL REFERENCES food_items(id),
  component_code        text NOT NULL REFERENCES food_components(code),
  amount_eaten          amount_eaten NOT NULL,
  is_substitution       boolean NOT NULL DEFAULT false,
  notes                 text
);

-- Standing accommodations (allergy swaps, disability modifications, and so on).
CREATE TABLE dietary_accommodations (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id               uuid NOT NULL REFERENCES children(id),
  alert_id               uuid REFERENCES child_alerts(id),
  replaces_component     text REFERENCES food_components(code),
  replaces_food_item_id  uuid REFERENCES food_items(id),
  substitute_food_item_id uuid REFERENCES food_items(id),
  reason                 substitution_reason NOT NULL,
  medical_statement_id   uuid REFERENCES documents(id),
  valid_during           daterange NOT NULL,
  CHECK (reason NOT IN ('allergy','disability') OR medical_statement_id IS NOT NULL)
);

-- Infants follow a different meal pattern and are fed on demand.
CREATE TABLE infant_feedings (
  id                uuid PRIMARY KEY,          -- client-generated
  center_id         uuid NOT NULL REFERENCES centers(id),
  child_id          uuid NOT NULL REFERENCES children(id),
  fed_at            timestamptz NOT NULL,
  feeding_type      feeding_type NOT NULL,
  amount_oz         numeric(4,1),
  food_item_id      uuid REFERENCES food_items(id),
  supplied_by       supplied_by NOT NULL,      -- claim rules differ by who supplied the formula or milk
  fed_by_staff      uuid REFERENCES staff(id),
  meal_service_id   uuid REFERENCES meal_services(id),   -- set when this feeding counts as a claimed meal
  notes             text
);
CREATE INDEX infant_feedings_child_idx ON infant_feedings (child_id, fed_at);

-- 7f. Monthly claims ---------------------------------------------------
CREATE TABLE claims (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id          uuid NOT NULL REFERENCES centers(id),
  claim_month        date NOT NULL CHECK (claim_month = date_trunc('month', claim_month)::date),
  status             claim_status NOT NULL DEFAULT 'draft',
  days_of_operation  smallint,
  total_amount       numeric(10,2),
  submitted_at       timestamptz,
  submitted_by       uuid REFERENCES users(id),
  state_confirmation text,
  locked_at          timestamptz,
  UNIQUE (center_id, claim_month)
);
CREATE TABLE claim_lines (                      -- frozen totals as submitted
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  claim_id       uuid NOT NULL REFERENCES claims(id),
  meal_type      meal_type NOT NULL,
  category       eligibility_category NOT NULL,
  meals_claimed  integer NOT NULL,
  rate_dollars   numeric(8,4) NOT NULL,        -- rate in force at submission
  amount         numeric(10,2) NOT NULL,
  UNIQUE (claim_id, meal_type, category)
);
CREATE TABLE claim_enrollment_counts (          -- enrollment and attendance figures the claim form asks for
  claim_id             uuid NOT NULL REFERENCES claims(id),
  category             eligibility_category NOT NULL,
  enrolled_children    integer NOT NULL,
  average_daily_attendance numeric(6,2),
  PRIMARY KEY (claim_id, category)
);
CREATE TABLE claim_included_meals (             -- exactly which meal records went into a claim
  claim_id              uuid NOT NULL REFERENCES claims(id),
  child_meal_record_id  uuid NOT NULL REFERENCES child_meal_records(id),
  PRIMARY KEY (claim_id, child_meal_record_id)
);

-- Problems found by the pre-submission check, so staff can fix them first.
CREATE TABLE claim_validation_issues (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id       uuid NOT NULL REFERENCES centers(id),
  claim_id        uuid REFERENCES claims(id),
  service_date    date,
  child_id        uuid REFERENCES children(id),
  meal_service_id uuid REFERENCES meal_services(id),
  code            text NOT NULL,               -- MISSING_COMPONENT, ELIGIBILITY_EXPIRED, NOT_PRESENT, TOO_MANY_MEALS,
                                               -- AGE_GROUP_MISMATCH, NO_MENU, UNFINALIZED_DAY, MISSING_MEDICAL_STATEMENT
  severity        issue_severity NOT NULL,
  message         text NOT NULL,
  resolved_by     uuid REFERENCES users(id),
  resolved_at     timestamptz
);
CREATE INDEX claim_issues_open_idx ON claim_validation_issues (center_id, service_date) WHERE resolved_at IS NULL;

-- =====================================================================
-- 8. VIEWS
-- =====================================================================

-- Eligibility category in force for a child on a date (used to snapshot into meal records).
CREATE FUNCTION eligibility_on(p_child uuid, p_date date)
RETURNS eligibility_category LANGUAGE sql STABLE AS $$
  SELECT category FROM eligibility_determinations
  WHERE child_id = p_child AND effective_on <= p_date AND p_date < expires_on
  ORDER BY effective_on DESC LIMIT 1
$$;

-- Age group in force for a child on a date.
CREATE FUNCTION cacfp_age_group_on(p_child uuid, p_date date)
RETURNS smallint LANGUAGE sql STABLE AS $$
  SELECT g.id FROM children c
  JOIN cacfp_age_groups g
    ON (extract(year FROM age(p_date, c.date_of_birth)) * 12
        + extract(month FROM age(p_date, c.date_of_birth))) BETWEEN g.min_months AND g.max_months
  WHERE c.id = p_child
$$;

-- Daily point-of-service counts: the numbers behind the monthly claim.
CREATE VIEW v_daily_meal_counts AS
SELECT ms.center_id, ms.service_date, ms.meal_type, r.eligibility_category, r.age_group_id,
       count(*) FILTER (WHERE r.is_claimable) AS meals_claimable,
       count(*)                               AS records
FROM child_meal_records r
JOIN meal_services ms ON ms.id = r.meal_service_id
GROUP BY ms.center_id, ms.service_date, ms.meal_type, r.eligibility_category, r.age_group_id;

-- Live staff-to-child ratio per classroom.
CREATE VIEW v_classroom_ratio_now AS
SELECT c.id AS classroom_id, c.name, c.ratio_children_per_staff,
       coalesce(k.children_in, 0) AS children_in,
       coalesce(s.staff_in, 0)    AS staff_in,
       coalesce(s.staff_in, 0) * c.ratio_children_per_staff >= coalesce(k.children_in, 0) AS within_ratio
FROM classrooms c
LEFT JOIN (SELECT classroom_id, count(*) AS children_in
           FROM attendance_records
           WHERE service_date = current_date AND status = 'present' AND checked_out_at IS NULL
           GROUP BY classroom_id) k ON k.classroom_id = c.id
LEFT JOIN (SELECT classroom_id, count(*) AS staff_in
           FROM time_entries WHERE clock_out_at IS NULL AND classroom_id IS NOT NULL
           GROUP BY classroom_id) s ON s.classroom_id = c.id;

-- Invoice balances.
CREATE VIEW v_invoice_balances AS
SELECT i.id AS invoice_id, i.account_id, i.invoice_number, i.due_on, i.status,
       coalesce(l.total, 0)              AS total_cents,
       coalesce(p.paid, 0)               AS paid_cents,
       coalesce(l.total, 0) - coalesce(p.paid, 0) AS balance_cents
FROM invoices i
LEFT JOIN (SELECT invoice_id, sum(amount_cents) AS total FROM invoice_lines GROUP BY invoice_id) l ON l.invoice_id = i.id
LEFT JOIN (SELECT pa.invoice_id, sum(pa.amount_cents) AS paid
           FROM payment_allocations pa JOIN payments pm ON pm.id = pa.payment_id AND pm.voided_at IS NULL
           GROUP BY pa.invoice_id) p ON p.invoice_id = i.id;

-- Staff certifications that are expired or expire within 60 days.
CREATE VIEW v_cert_alerts AS
SELECT s.id AS staff_id, s.first_name, s.last_name, ct.label, sc.expires_on,
       (sc.expires_on - current_date) AS days_left
FROM staff_certifications sc
JOIN staff s ON s.id = sc.staff_id AND s.terminated_on IS NULL
JOIN certification_types ct ON ct.id = sc.cert_type_id
WHERE sc.expires_on <= current_date + 60;
